# Generated by Filter Pipeline: 2025-09-29 12:35:44.778815
# Top 22 from S&P 500 filtering

STOCKS = ['ANET', 'DDOG', 'DELL', 'INTC', 'LRCX', 'MCHP', 'NKE', 'SLB', 'STZ', 'TTD', 'UAL', 'WDC', 'ALGN', 'HUM', 'ABNB', 'AMAT', 'ALB', 'APO', 'BIIB', 'CNC', 'BAC', 'DAL']

EDGE_REASON = {
    "ANET": "IV 44%, 100 strikes, score 100",
    "DDOG": "IV 42%, 114 strikes, score 100",
    "DELL": "IV 41%, 112 strikes, score 100",
    "INTC": "IV 68%, 114 strikes, score 100",
    "LRCX": "IV 41%, 116 strikes, score 100",
    "MCHP": "IV 44%, 106 strikes, score 100",
    "NKE": "IV 56%, 102 strikes, score 100",
    "SLB": "IV 41%, 104 strikes, score 100",
    "STZ": "IV 46%, 114 strikes, score 100",
    "TTD": "IV 56%, 116 strikes, score 100",
    "UAL": "IV 63%, 104 strikes, score 100",
    "WDC": "IV 53%, 174 strikes, score 100",
    "ALGN": "IV 44%, 124 strikes, score 95",
    "HUM": "IV 58%, 136 strikes, score 95",
    "ABNB": "IV 33%, 108 strikes, score 90",
    "AMAT": "IV 40%, 118 strikes, score 90",
    "ALB": "IV 63%, 78 strikes, score 90",
    "APO": "IV 38%, 104 strikes, score 90",
    "BIIB": "IV 36%, 104 strikes, score 90",
    "CNC": "IV 54%, 74 strikes, score 90",
    "BAC": "IV 30%, 110 strikes, score 90",
    "DAL": "IV 54%, 74 strikes, score 90",
}
